### ISSUE TITLE
Smart Restart not working as expected

### ISSUE THREAD

**Issue by harinathreddys401** [cubandave/Jamf-Interaction-Toolkit#31] opened 2019-02-12 16:42 UTC
In 4.0.1 we are getting multiple restart prompts even through user already approved for restart. Smart restart not working as expected

**Comment by cubandave** [comment] 2019-02-13 14:28
unable to replicate asking for logs from @harinathreddys401

**Comment by cubandave** [comment] 2019-02-13 14:48
This was due to other policies running an oder version of UEX without that feature. Thanks for raising the Issue report!

Closing as expected behavior.

**Closed by cubandave** 2019-02-13 14:48 UTC
Labels: bug
